name: test_project
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  conduit: ^4.1.5
  jaguar_jwt: ^3.0.0

dev_dependencies:
  test: ^1.16.5